name: SonarCloud

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

env:
  PROJECT_KEY: renandpf_sgr-pedido
  PROJECT_NAME: sgr-pedido
  SONAR_HOST: https://sonarcloud.io
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0      
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Verify
        run: |
          export MAVEN_OPTS="
          -Dsonar.qualitygate.wait=true 
          -Dsonar.organization=renandpf 
          -Dsonar.projectKey=${{ env.PROJECT_KEY }} 
          -Dsonar.projectName=${{ env.PROJECT_NAME }} 
          -Dsonar.host.url=${{ env.SONAR_HOST }} 
          -Dsonar.token=${{ env.SONAR_TOKEN }}
          -Dsonar.coverage.exclusions=src/main/java/br/com/pupposoft/fiap/SgrPagamentoService.java,src/main/java/br/com/pupposoft/fiap/sgr/**dto**/**/*"
          mvn clean verify sonar:sonar